# Generated by Django 4.2.9 on 2024-02-02 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmanager',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.projectmanager'),
        ),
        migrations.RemoveField(
            model_name='developer',
            name='project',
        ),
        migrations.AddField(
            model_name='developer',
            name='project',
            field=models.ManyToManyField(to='projects.project'),
        ),
    ]
