# Generated by Django 4.2.9 on 2024-02-02 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_developer_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='project',
            field=models.ManyToManyField(blank=True, to='projects.project'),
        ),
    ]
